// <auto-generated />
using System;
using CaseritoApp.Catalog.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CaseritoApp.Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260725141228_CatalogAvisoVendido")]
    partial class CatalogAvisoVendido
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CaseritoApp.Catalog.Domain.Avisos.Aviso", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CiudadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Condicion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Estado")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EstadoModeracion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Visible");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("OrdenVentaId")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("VendedorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("VendedorId");

                    b.HasIndex("VendedorId", "Estado");

                    b.ToTable("Avisos", "catalog");
                });

            modelBuilder.Entity("CaseritoApp.Catalog.Domain.Avisos.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categorias", "catalog");
                });

            modelBuilder.Entity("CaseritoApp.Catalog.Domain.Avisos.Ciudad", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ciudades", "catalog");
                });

            modelBuilder.Entity("CaseritoApp.Catalog.Domain.Avisos.FotoAviso", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AvisoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AvisoId");

                    b.HasIndex("AvisoId", "Orden");

                    b.ToTable("FotosAviso", "catalog");
                });

            modelBuilder.Entity("CaseritoApp.Catalog.Domain.Moderacion.RegistroModeracion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("AvisoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ModeradorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReporteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AvisoId", "Fecha");

                    b.ToTable("RegistrosModeracion", "catalog");
                });

            modelBuilder.Entity("CaseritoApp.Catalog.Domain.Moderacion.ReporteAviso", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AvisoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Detalle")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Estado")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("ReportanteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ResueltoPorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AvisoId", "ReportanteId")
                        .IsUnique()
                        .HasFilter("[Estado] = N'Pendiente'");

                    b.HasIndex("Estado", "AvisoId");

                    b.ToTable("ReportesAviso", "catalog");
                });

            modelBuilder.Entity("CaseritoApp.Catalog.Domain.Avisos.Aviso", b =>
                {
                    b.OwnsOne("CaseritoApp.Catalog.Domain.Avisos.Dinero", "Precio", b1 =>
                        {
                            b1.Property<Guid>("AvisoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("PrecioMoneda");

                            b1.Property<decimal>("Monto")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PrecioMonto");

                            b1.HasKey("AvisoId");

                            b1.ToTable("Avisos", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("AvisoId");
                        });

                    b.Navigation("Precio")
                        .IsRequired();
                });

            modelBuilder.Entity("CaseritoApp.Catalog.Domain.Avisos.FotoAviso", b =>
                {
                    b.HasOne("CaseritoApp.Catalog.Domain.Avisos.Aviso", null)
                        .WithMany("Fotos")
                        .HasForeignKey("AvisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CaseritoApp.Catalog.Domain.Moderacion.ReporteAviso", b =>
                {
                    b.HasOne("CaseritoApp.Catalog.Domain.Avisos.Aviso", null)
                        .WithMany()
                        .HasForeignKey("AvisoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CaseritoApp.Catalog.Domain.Avisos.Aviso", b =>
                {
                    b.Navigation("Fotos");
                });
#pragma warning restore 612, 618
        }
    }
}
