// <auto-generated />
using System;
using CaseritoApp.Chat.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CaseritoApp.Chat.Infrastructure.Migrations
{
    [DbContext(typeof(ChatDbContext))]
    partial class ChatDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("chat")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("SecuenciaMensajes", "chat");

            modelBuilder.Entity("CaseritoApp.Chat.Domain.Conversaciones.Conversacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AvisoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompradorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreadaEn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("UltimaActividadEn")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("UltimaSecuencia")
                        .HasColumnType("bigint");

                    b.Property<long>("UltimaSecuenciaLeidaComprador")
                        .HasColumnType("bigint");

                    b.Property<long>("UltimaSecuenciaLeidaVendedor")
                        .HasColumnType("bigint");

                    b.Property<Guid>("VendedorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("CompradorId", "AvisoId")
                        .IsUnique()
                        .HasDatabaseName("UX_Conversaciones_Comprador_Aviso");

                    b.HasIndex("CompradorId", "UltimaActividadEn", "Id");

                    b.HasIndex("VendedorId", "UltimaActividadEn", "Id");

                    b.ToTable("Conversaciones", "chat");
                });

            modelBuilder.Entity("CaseritoApp.Chat.Domain.Conversaciones.Mensaje", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClaveIdempotencia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConversacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("EnviadoEn")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RemitenteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Secuencia")
                        .HasColumnType("bigint");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ConversacionId", "Secuencia")
                        .IsUnique();

                    b.HasIndex("ConversacionId", "RemitenteId", "ClaveIdempotencia")
                        .IsUnique()
                        .HasDatabaseName("UX_Mensajes_Conversacion_Remitente_Clave");

                    b.ToTable("Mensajes", "chat");
                });

            modelBuilder.Entity("CaseritoApp.Chat.Infrastructure.TiempoReal.EntregaTiempoReal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConversacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreadaEn")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Intentos")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LeaseHasta")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("MensajeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ProcesadaEn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ProximoIntentoEn")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("Secuencia")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MensajeId")
                        .IsUnique();

                    b.HasIndex("Secuencia", "Id");

                    b.HasIndex("ProcesadaEn", "ProximoIntentoEn", "LeaseHasta");

                    b.ToTable("EntregasTiempoReal", "chat");
                });

            modelBuilder.Entity("CaseritoApp.Chat.Domain.Conversaciones.Mensaje", b =>
                {
                    b.HasOne("CaseritoApp.Chat.Domain.Conversaciones.Conversacion", null)
                        .WithMany()
                        .HasForeignKey("ConversacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CaseritoApp.Chat.Infrastructure.TiempoReal.EntregaTiempoReal", b =>
                {
                    b.HasOne("CaseritoApp.Chat.Domain.Conversaciones.Mensaje", null)
                        .WithMany()
                        .HasForeignKey("MensajeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
