// <auto-generated />
using System;
using CaseritoApp.Notifications.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CaseritoApp.Notifications.Infrastructure.Migrations
{
    [DbContext(typeof(NotificationsDbContext))]
    [Migration("20260809155641_NotificationsWebPush")]
    partial class NotificationsWebPush
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("notifications")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CaseritoApp.Notifications.Domain.Busquedas.BusquedaGuardada", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Category");

                    b.Property<string>("Ciudad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("City");

                    b.Property<DateTimeOffset>("CreadaEn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("EstadoProducto")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("EstadoProducto");

                    b.Property<string>("PalabraClave")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Keyword");

                    b.Property<decimal?>("PrecioMaximo")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("MaxPrice");

                    b.Property<decimal?>("PrecioMinimo")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("MinPrice");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("SavedSearches", "notifications");
                });

            modelBuilder.Entity("CaseritoApp.Notifications.Domain.Notificaciones.Notificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreadaEn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedAt");

                    b.Property<Guid>("DestinatarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EntidadRelacionadaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RelatedEntityId");

                    b.Property<bool>("Leida")
                        .HasColumnType("bit")
                        .HasColumnName("IsRead");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Body");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("DestinatarioId", "CreadaEn", "Id");

                    b.HasIndex("DestinatarioId", "Leida", "CreadaEn");

                    b.ToTable("Notifications", "notifications");
                });

            modelBuilder.Entity("CaseritoApp.Notifications.Domain.PuntosEncuentro.PuntoEncuentroSeguro", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("City");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Address");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Name");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Ciudad", "Activo");

                    b.ToTable("SafeMeetingPoints", "notifications");
                });

            modelBuilder.Entity("CaseritoApp.Notifications.Domain.Push.IntencionPush", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConversacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreadaEn")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DestinatarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DisponibleEn")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Intentos")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LeaseHasta")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ProcesadaEn")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("Secuencia")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EventoId")
                        .IsUnique();

                    b.HasIndex("ProcesadaEn", "DisponibleEn", "LeaseHasta");

                    b.ToTable("PushIntents", "notifications");
                });

            modelBuilder.Entity("CaseritoApp.Notifications.Domain.Push.SuscripcionPush", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("ActualizadaEn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreadaEn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DispositivoId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset?>("RevocadaEn")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Activa");

                    b.HasIndex("UsuarioId", "DispositivoId")
                        .IsUnique();

                    b.ToTable("PushSubscriptions", "notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
